name: "Cross project models checker enhanced"

on:
  pull_request:
    branches:
      - main

jobs:
  compare_files:
    runs-on: ubuntu-latest
    name: Run checking process for cross project models
    steps:
      - uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: Compare with static list
        run: |
          # Define paths for the static and generated CSV files
          STATIC_LIST="cross_project/list_of_cross_model_v3.csv"

          # Extract models from static list, ignoring headers
          STATIC_MODELS=$(awk -F',' 'NR>1 {print $1}' "$STATIC_LIST")

          # Extract changed models from the list of changed files
          CHANGED_MODELS=$(echo "${{ steps.changed-files.outputs.all_changed_files }}" | awk -F'[/.]' '{print $(NF-1)}' | sort -u)

          # Find matches between static models and changed models
          MATCHES=$(echo "$CHANGED_MODELS" | grep -Fx -f <(echo "$STATIC_MODELS") || true)

          if [ -n "$MATCHES" ]; then
            echo "Found matches: $MATCHES"

            PR_LINK="${{ github.event.pull_request.html_url }}"
            MESSAGE="Hi <users/all>\nModels that are used in cross project have been changed in this PR: $PR_LINK.\nThe models are mentioned below, please check it:\n"

            while IFS=',' read -r model reference origin_repo; do
              if echo "$MATCHES" | grep -qx "$model"; then
                MESSAGE+="* \`$model\` that referred in \`$reference\` (origin repo is \`$origin_repo\`)\n"
              fi
            done < <(tail -n +2 "$STATIC_LIST")

            echo "Final message: $MESSAGE"

            curl -X POST -H 'Content-Type: application/json' \
              -d '{"text": "'"$MESSAGE"'"}' \
              "${{ secrets.MODELS_CROSS_PROJECT }}"
          else
            echo "No matches found."
          fi
