name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  compare_files:
    runs-on: ubuntu-latest
    name: Check models cross project v2
    steps:
      - uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: Print changed files for debugging
        run: echo "${{ steps.changed-files.outputs.all_changed_files }}"
        
      - name: Compare with static list
        id: compare
        run: |
          # Define paths for the static and generated CSV files
          STATIC_LIST="cross_project/list_of_cross_model_v3.csv"
          
          MATCHES=""
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            for static_item in "${STATIC_LIST[@]}"; do
              if [[ "$file" == *"$static_item"* ]]; then
                MATCHES="${MATCHES}\n"* $static_item"
              fi
            done
          done
          echo "MATCHES=$MATCHES" >> $GITHUB_ENV
      
      - name: Send Alert
        run: |
          if [[ -n "${{ env.MATCHES }}" ]]; then
            curl -X POST -H "Content-Type: application/json" \
            -d "{\"text\": \"Hi \u003cusers/all\u003e\nModels that are used in cross project have been changed in this PR: https://github.com/Jomen034/git_test/pull/26.\nThe models are mentioned below, please check it:${{ env.MATCHES }}\"}" \
            "${{ secrets.MODELS_CROSS_PROJECT }}"
          fi

