name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  # ------------------------------------------------------------------------------------------------------------------------------------------------
  # Event `pull_request`: Compare the last commit of the main branch or last remote commit of the PR branch -> to the current commit of a PR branch.
  # ------------------------------------------------------------------------------------------------------------------------------------------------
  changed_files:
    runs-on: ubuntu-latest  # windows-latest || macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: Process and save changed files to CSV
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          # Create the directory if it doesn't exist
          mkdir -p models_cross_project
          
          # Specify the CSV file path in the models_cross_project directory
          CSV_FILE="models_cross_project/list_of_changed_files.csv"
          
          # Add header to CSV file
          echo "changed_files" > $CSV_FILE
          
          # Process each changed file path: remove path, extensions, and avoid duplicates
          echo "${ALL_CHANGED_FILES}" | tr ' ' '\n' | awk -F/ '{print $NF}' | awk -F. '{print $1}' | sort | uniq >> $CSV_FILE
          
      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "actions@github.com"
          
          # Checkout the branch that triggered the workflow
          git checkout ${{ github.head_ref }}
          
          git add models_cross_project/list_of_changed_files.csv
          git commit -m "Add list of changed files"
          
          # Push the changes to the branch
          git push origin HEAD:${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}