name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  # ------------------------------------------------------------------------------------------------------------------------------------------------
  # Event `pull_request`: Compare the last commit of the main branch or last remote commit of the PR branch -> to the current commit of a PR branch.
  # ------------------------------------------------------------------------------------------------------------------------------------------------
  changed_files:
    runs-on: ubuntu-latest  # windows-latest || macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: List and save all changed files to CSV
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          # Create output directory if it doesn't exist
          mkdir -p output
          
          # Specify the CSV file path in the output directory
          CSV_FILE="output/changed_files.csv"
          
          # Add header to CSV file
          echo "File Path" > $CSV_FILE
          
          # Append each changed file path to the CSV file
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file" >> $CSV_FILE
          done

      - name: Upload CSV file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: changed-files
          path: output/changed_files.csv